par(mfrow=c(2,2),mar = c(4, 4, 2, 1))
plot(dt$dateTime, dt$Global_active_power, type="n", xlab="", ylab="Global Active Power")
lines(dt$dateTime, dt$Global_active_power)
plot(dt$dateTime, dt$Voltage, type="n", xlab="datetime", ylab="Voltage")
lines(dt$dateTime, dt$Voltage)
plot(dt$dateTime, dt$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering")
lines(dt$dateTime, dt$Sub_metering_1, col="black")
lines(dt$dateTime, dt$Sub_metering_2, col="red")
lines(dt$dateTime, dt$Sub_metering_3, col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"),lty=1)
plot(dt$dateTime, dt$Global_reactive_power, type="n", xlab="datetime", ylab="Global_reactive_power")
lines(dt$dateTime, dt$Global_reactive_power)
png(filename = paste(current.dir, "/plot4.png", sep=""), width=480, height = 480)
par(mfrow=c(2,2),mar = c(4, 4, 2, 1))
plot(dt$dateTime, dt$Global_active_power, type="n", xlab="", ylab="Global Active Power")
lines(dt$dateTime, dt$Global_active_power)
plot(dt$dateTime, dt$Voltage, type="n", xlab="datetime", ylab="Voltage")
lines(dt$dateTime, dt$Voltage)
plot(dt$dateTime, dt$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering")
lines(dt$dateTime, dt$Sub_metering_1, col="black")
lines(dt$dateTime, dt$Sub_metering_2, col="red")
lines(dt$dateTime, dt$Sub_metering_3, col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"),lty=1)
plot(dt$dateTime, dt$Global_reactive_power, type="n", xlab="datetime", ylab="Global_reactive_power")
lines(dt$dateTime, dt$Global_reactive_power)
dev.off()