plot(dt$dateTime, dt$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering")
lines(dt$dateTime, dt$Sub_metering_1, col="black")
lines(dt$dateTime, dt$Sub_metering_2, col="red")
lines(dt$dateTime, dt$Sub_metering_3, col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"),lty=1)
png(filename = paste(current.dir, "/plot3.png", sep=""), width=480, height = 480)
plot(dt$dateTime, dt$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering")
lines(dt$dateTime, dt$Sub_metering_1, col="black")
lines(dt$dateTime, dt$Sub_metering_2, col="red")
lines(dt$dateTime, dt$Sub_metering_3, col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"),lty=1)
dev.off()